# -*- coding: utf-8 -*-
"""week 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1caLya0lq9i9fZAkrWyVj3BgSODC0rmeo
"""

import numpy as np
import pandas as pd
import math

# Week 1 Dataset
df = pd.read_csv('https://raw.githubusercontent.com/MichiganDataScienceTeam/f25-building-ml-models/refs/heads/main/week-1/dataset.csv')

# TODO: First view the input data using head(), then store the top 5 inputs in a np array
# Hint: List[:x] can extract the first x elements of a python list

def sigmoid(x: int) -> float:
  """Sigmoid activation function."""
  # TODO: Write the activation function
  return 0.0

class Perceptron:
  """Neuron class object representing perceptron."""

  def __init__(self, num_inputs: int, weights = None) -> None:
    """Init weights and other information."""

    self.num_inputs = num_inputs

    # TODO: declare a variable to store weights similar to how num_inputs is stored
    # Define random weights in shape (1, num_inputs)

  def feed_forward(self, inputs: np.array) -> float:
    """Forward propogation step."""

    output = None

    # TODO: complete feed forward algorithm below
    return output

def main():
  """Test Perceptron class here."""

  # TODO: Declare your perceptron class below, run your feed_forward algorithm
  # BONUS: declare an array of weights to pass into your perceptron so the output of the forward pass is 0.5

main()

